[project]
name = "udfs-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fused[all]>=1.14.2",
    "jupyterlab>=4.3.6",
    "mcp[cli]>=1.4.1",
]

[tool.uv.sources]
fused = { path = "../fused-py" }
